# Example config file for running the automated starships pipeline

# -----------------------------------------------------------
# --- Main parameters ---
# -----------------------------------------------------------

# Planet name 
# This is used to fetch information in ExoFile, and also to save the results, 
# with the spaces replaced by '_'
pl_name: WASP-127 b

# Observation directory
# This is the directory where the observations are stored
# if null, takes from projects/def-rdoyon/shared/NIRPS-APERO/WASP-127b/


# ----------------------------------------------------------- OLD PARAMETERS

# FILE ORGANIZATION
obs_dir: null # if null, takes from sbatch file 'projects/def-dlafre/fgenest/nirps/WASP-127b/' # starting from projects, home will be added in pipeline
star_dir: "/WASP127"

out_dir: null # if null, will save to def-dlafre/shared/INSTRUMENT/REDUCTION_NAME/PLANET_NAME...

# GLOBAL PARAMETERS USED IN MULTIPLE STAGES
instrument: 'NIRPS-APERO'
visit_name: [] # leave as [] if file lists not yet generated

kind_trans: 'transmission'
coeffs: [0.02703969,  1.10037972, -0.96372403,  0.28750393]
ld_model: 'nonlinear'
kind_res: 'high'

# --------------------------------------------------------------------------------------------------
# REDUCTION INPUTS

reduction: 'one_visit_full'
mask_tellu: [0.2, 0.5]
mask_wings: [0.9, 0.95, 0.97]
n_pc: [0, 1, 2, 3, 4] # given as a list to test each
iout_all: ['all']
clip_ratio: 6
clip_ts: 6
unberv_it: True

idx_ord: [15, 33, 41]    # for output plots

# If you have already split files by visit (i.e., not left visit_name blank), you can specify exposures
# to remove for each night
bad_indexs: {
  # 'night1': [],
  # 'night2': [],
  # 'night3': [],
} 

# --------------------------------------------------------------------------------------------------
# MODEL INPUTS : see other YAML file

# --------------------------------------------------------------------------------------------------
# CCF INPUTS

# for NIRPS, step size of 
RV_range: [-150, 151] # range used to build Kp_array
RV_step: 2 # step size

RV_lim: 100 # used for ttest map
Kp_step: 5 # used for ttest map
# --------------------------------------------------------------------------------------------------
# OTHER PLANET PARAMETERS
# units must be inputted in astropy format

pl_params:
  M_star: 
    value: 0.950 
    unit: M_sun

  R_star: 
    value: 1.333
    unit: R_sun
  
  M_pl: 
    value: 0.165
    unit: M_jup
  
  R_pl: 
    value: 1.311
    unit: R_jup
  
  RV_sys: 
    value: -8.86
    unit: km/s
  
  mid_tr: 
    value: 2459575.9239004
    unit: d
  
  t_peri: 
    value: 2459575.9239004
    unit: d
  
  trandur: 
    value: 4.3529
    unit: h
  
  period: 
    value: 4.1780625
    unit: d
  
  excent: # LEAVE AS DEFAULT
    value: 0.0
    unit: null
  
  incl: 
    value: 87.84
    unit: deg
  
  Teff: 
    value: 5842
    unit: null
  
  # A_star: null
  # surf_grav: null
  # logg: null
  # gp: null
  
  Tp: 
    value: 1400 
    unit: K
  w: # LEAVE AS DEFAULT
    value: -90
    unit: deg
  ap: 
    value: 0.04840
    unit: au
  
  # H: null
  # sync_equat_rot_speed: null
