limP: [-10, 2]    # pressure log range, standard
n_pts: 50         # pressure n_points, standard
mode: 'high'

chemical_equilibrium: True
dissociation: False
line_opacities: ['H2O']
line_lists: {} # to circumvent automatic line list generation
continuum_opacities: []
other_species: []

species_vmr: {} # must be provided if chemical_equilibrium is False, will be inputted as 10**vmr

opacity_sampling: 1

star_wv: null
star_flux: null

linelist_names: {'high': null, 'low': null}

fct_star_global: {'high': null, 'low': null}
atmo_high: null
atmo_low: null
T_eq: 1000
p_cloud: 0.1  # cloud deck, bar
P0: 0.1
gamma_scat: -4 # "haze"
scat_factor: 0 
C/O: 0.54
Fe/H: 0

wind: null

# Note - specifying instrument will mean model will automatically be comvolved with instrument
# if not specifying instrument, must specify wl_range and Raf
instrument: 'NIRPS-APERO'
kind_trans: 'transmission'
wl_range: null
Raf: null